### ISSUE TITLE
Suivi du projet

### ISSUE THREAD

**Issue by Royoyo** [Royoyo/ProjetSio#42]
Page en ligne pour la maquette fonctionnelle : 
[http://royoyo.github.io/ProjetSio/](http://royoyo.github.io/ProjetSio/)

##### Pages Login
- [x]  [Page de connexion](https://github.com/Royoyo/ProjetSio/issues/23)
- [x]  [Page de réinitialisation de mot de passe](https://github.com/Royoyo/ProjetSio/issues/23)

##### Pages Administrateur
- [x]   [Page liste des utilisateur] (https://github.com/Royoyo/ProjetSio/issues/22)
- [x]  [Page création d'utilisateur](https://github.com/Royoyo/ProjetSio/issues/24)
- [x]  Page de consultation d'un utilisateur 

##### Pages Planificateur
- [x]  [Page d'accueil] (https://github.com/Royoyo/ProjetSio/issues/26)
- [x]  Pages de gestion des classe d'élèves ***(En travaux)***
- [x]  Pages de gestion des matières enseignées ***(En travaux)***
- [x]  Pages de gestion des enseignants ***(En travaux)***
- [x]  Pages de gestion des années scolaires ***(En travaux)***

##### Pages Enseignant 
- [x] [Page d'accueil] (https://github.com/Royoyo/ProjetSio/issues/25)
- [x] Page d'indication des indisponibilités
- [x] [Page de consultation de la planification de l'enseignant](https://github.com/Royoyo/ProjetSio/issues/39)
- [ ] Page de consultation de la planification des classes affectées à l'enseignant

##### Autres pages
- [ ] Page Activation de compte
- [ ] Pages Documentation

#### Code SQL

- [ ] Initialisation des tables utilisateurs ***(En travaux)***
- [ ] Initialisation des objets métiers ***(En travaux)***

#### Css unifié

- [x] création d'un style de tableau unifié ***(En travaux)***
- [x] Création d'un style de div centré unifié
- [x] Rajout d'un reset CSS + factorisation des styles css de chacuns

**Comment by taophp** [comment]
@Royoyo tu devrais lier (je veux dire un lien HTML) les entrées de tes listes avec les tickets correspondants. Cela permettrait de passer facilement de la vue globale (ici) aux détails.

**Comment by Royoyo** [comment]
j'ai configuré une github page pour avoir notre maquette fonctionnelle en ligne et automatiquement mise à jour : [http://royoyo.github.io/ProjetSio/](http://royoyo.github.io/ProjetSio/)

**Comment by taophp** [comment]
Excellent!

**Comment by Royoyo** [comment]
La plupart des pages html étant terminées, je vais combler les trous pour que l'on puisse s'attaquer au code PHP générant les pages.

**Comment by Royoyo** [comment]
La page maquette github ne fonctionnant apparemment pas voici la version actuelle de la maquette hébergée chez moi : http://guillaumehaag.fr/SIO/Projet/Pages%20Login/Page-connexion-Damien.html

**Comment by taophp** [comment]
Est-ce à dire que nous pouvons passer à l'étape de validation de la maquette fonctionnelle ?

**Comment by Royoyo** [comment]
Presque, il faut juste  que je comble les trous des pages manquantes et que je règles quelques problèmes de styles pour certaines pages. D'ici la fin de semaine, voir le début de semaine prochaine  la maquette sera prête.

**Comment by Royoyo** [comment]
Voilà, la maquette fonctionnelle est en ligne [ici](http://guillaumehaag.fr/SIO/Projet/Pages%20Login/Page-connexion-Damien.html)
